### ISSUE TITLE
impl FromStr for IString

### ISSUE THREAD

**Issue by OmmyZhang** [yewstack/implicit-clone#26]
https://doc.rust-lang.org/std/str/trait.FromStr.html

reason: both number and IString are widely used for vaule of form input, but number types only impl FromStr, not FromString or TryFromString. If IString impl FromStr (just like String), we can write something like:

```rust
fn input_onchange<T: FromStr + 'static>(setter: UseStateSetter<T>) -> Callback<Event> {
```

**Comment by OmmyZhang** [comment]
Now I have to write something like this:

```rust
fn input_onchange<T, S>(setter: UseStateSetter<T>) -> Callback<Event>
where T: From<S> + 'static, S: FromStr, <S as FromStr>::Err: std::fmt::Debug
{
```

or impl my own trai MyFromStr.

It's so strange.

**Comment by kirillsemyonkin** [comment]
It is fixed in #21, but may be not released yet. I'll keep the issue open for a little bit until I or someone else get to releasing it.

**Comment by OmmyZhang** [comment]
Sorry for not noticing this...

**Comment by cecton** [comment]
@kirillsemyonkin I usually release pretty quick with cargo-release. If you want I can do it. 

(Ideally we should have a changelog and everything but it's a bit of work and there shouldn't be much changes on this project...)

**Comment by kirillsemyonkin** [comment]
@cecton I want #18 to be done quickly and then I or you can release 0.4.1. But if its a hurry we can split into two releases I guess.

**Comment by kirillsemyonkin** [comment]
Done in 0.4.1
